In [1]:
import pandas as pd

In [4]:
dataset = pd.read_csv("for_visualization_food.csv")

In [5]:
dataset.head()

,Unnamed: 0,text,prompt,group_num,image_num,vector,x,y
0,0,a dog laying next to a birthday cake,a dog is eating a cake,0,0,[-3.15368325e-01 1.65492833e+00 -3.76081681e+...,-22.215971,27.099045
1,1,a black and white dog standing next to a birth...,a dog is eating a cake,0,1,[-1.9701213 1.573011 -4.1248627 -0.875087...,-9.566553,41.481700
2,2,a dog laying on a table with a birthday cake,a dog is eating a cake,0,2,[-3.10401648e-01 -1.22788347e-01 -2.96193337e+...,-28.846928,11.488414
3,3,a dog laying on the ground next to a cake,a dog is eating a cake,0,3,[ 4.9954167e-01 1.9734832e+00 -4.0621505e+00 ...,-21.019585,24.004442
4,4,a dog sitting at a table with a plate of food,a dog is eating a cake,0,4,[ 7.9953337e-01 4.8825336e-01 -4.7866669e+00 ...,27.074589,18.197746

In [7]:
dataset= dataset.loc[dataset['prompt']=='a dog is eating a cheese cake']
dataset.head()

,Unnamed: 0,text,prompt,group_num,image_num,vector,x,y
3200,3200,a dog looking at a cheesecake with strawberrie...,a dog is eating a cheese cake,4,0,[ 7.27219999e-01 1.64846003e+00 -1.97036004e+...,-11.821568,-101.590880
3201,3201,a dog is looking at a cake with strawberries o...,a dog is eating a cheese cake,4,1,[ 2.26520017e-01 7.61779964e-01 -2.68713999e+...,-60.833164,-52.831894
3202,3202,a dog with a piece of cheese and strawberries ...,a dog is eating a cheese cake,4,2,[-2.29683325e-01 6.75436676e-01 -2.04988337e+...,7.073134,-58.933132
3203,3203,a dog eating a piece of cake on a table,a dog is eating a cheese cake,4,3,[ 4.56216693e-01 -6.76916778e-01 -2.89418340e+...,84.436430,-15.055461
3204,3204,a dog sitting on a table eating a piece of che...,a dog is eating a cheese cake,4,4,[ 9.59571421e-01 1.03748572e+00 -3.01354289e+...,-55.766730,-13.911123

In [11]:
for i,row in dataset.iterrows():
    if i<3220: print(row['text'])

a dog looking at a cheesecake with strawberries on it
a dog is looking at a cake with strawberries on it
a dog with a piece of cheese and strawberries on a plate
a dog eating a piece of cake on a table
a dog sitting on a table eating a piece of cheesecake
a black and white dog eating a piece of cheese and a strawberry
a dog looking at a cake with berries on it
a dog sitting in front of a plate with a piece of cake on it
a brown and white dog standing next to a plate of food
a dog sniffing a cheesecake on a table
a dog licking a piece of cake on a table
a slice of cheesecake with raspberries on a white plate
a black and white dog with a piece of cheese on a plate
a dog is looking at a piece of cake on a plate
a dog laying on a bed next to a piece of cheesecake
a piece of cheese and a piece of cheese on a plate
a dog looking at a plate of cheese and a piece of cake
a piece of cheesecake on a plate with a flower
a brown and white dog looking at a piece of cake
a pug looking at a piece of cheesecake on a plate